baseURL = 'https://jenkaj-lab.github.io/jenkaj-lab/'
canonifyURLs = true
languageCode = 'en-gb'
title = 'My MITRE ATT&CK Journey'
theme = 'maverick'
paginate = 20

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/'
    weight = 10
  [[menus.footer]]
    name = 'Disclaimer'
    pageRef = '/disclaimer'
    weight = 20
